### ISSUE TITLE
Let description lists have codeblocks

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-docs#1002]
Unless I misunderstand, the definitions in a `DescriptionList` element can't have codeblocks. It's not a common need, but it could be useful in long explanatory articles.

**Comment by imiric** [comment]
Hey, as mentioned in https://github.com/grafana/k6-docs/pull/1003#discussion_r1089087450, I think we should close this issue, since we shouldn't need to implement code blocks in description list definitions. `<dl>` elements should be used for short term descriptions, so we shouldn't need to support advanced formatting in `<dd>` elements.

**Comment by MattDodsonEnglish** [comment]
Fair enough. I still think it's reasonable to expect all components to parse recursively, but you've convinced me there's truly no use for this particular case :-)
