### ISSUE TITLE
Document how VUs are cycled in arrival-rate executors

### ISSUE THREAD

**Issue by na--** [grafana/k6-docs#136]
Prompted by https://github.com/loadimpact/k6/pull/1623#discussion_r505206848, we should make sure to explain that the arrival-rate executors are going to cycle over all of the initialized VUs, given enough time, even if they only need a small fraction of them at any given point to run their allotted iterations per second.

**Comment by mstoykov** [comment]
I guess I have to comment here instead of at https://github.com/grafana/k6-docs/pull/1016#discussion_r1091717179. 

I am not certain documenting the specificity of the VUs being cycled is a good idea. This is an implementation detail that *might* change in the future. 

It also has close to zero actionable  things you can do with that. Even the linked example is arguably not great because it depends on the data and each iteration being uniformly taking time. 

This seems to be based on the usual "misconception" that you should map 1 user to 1 VU for the whole duration of the test/scenario. Which IME is not great and does not scale either way. 

As such I prefer if instead of documenting the specific cycling of VUs to more or less say "there is no guarantee on which number of VU will run which number of iteration for any given scenario. A uniform distribution of the iterations over the VUs is guaranteed and should not be depended on. "

**Comment by na--** [comment]
Good points, I agree that we shouldn't document the current state, since it is indeed an implementation detail that we might decide to change in the future, e.g. to optimize the executor for higher throughput. Documenting the current implementation will almost prevent us from doing that, or at least make it an unnecessary breaking change. :+1: for something like this:
> There is no guarantee which VU will run which iteration for any given scenario. A uniform distribution of the iterations over the VUs is guaranteed and should not be depended on.

**Comment by MattDodsonEnglish** [comment]
Thanks to both of you for pointing this out. I've added this which I think is more useful and general than the original: https://github.com/grafana/k6-docs/commit/79c10d68667cb2be78c02b58214c1d3ec31e564c
