### ISSUE TITLE
Create page for k6/browser `ElementHandle|Frame|Page|Locator`'s `setChecked` methods

### ISSUE THREAD

**Issue by heitortsergent** [grafana/k6-docs#1666]
Related to https://github.com/grafana/k6-docs/pull/1664.

The docs are missing a page for the `setChecked` function for the `ElementHandle` object.

**Comment by heitortsergent** [comment]
@inancgumus @ankur22 we got some feedback that we had a 404 on the ElementHandle page and I think we're just missing a page for one of the functions here. I removed the link for now, would you be able to grab this issue? 🙇

**Comment by inancgumus** [comment]
It turns out that we don't publish `ElementHandle.setChecked` to users (it's not available on the browser module's Javascript API). Instead, we have `ElementHandle.check` and `ElementHandle.uncheck`. The difference of `setChecked` is that it _toggles_ input checkboxes.

Next steps:
- Publish `setChecked` to users
- Update the documentation

**Comment by inancgumus** [comment]
@heitortsergent This can be closed once the reviewers approve #1696 🎉
