### ISSUE TITLE
Document new kafka output configuration options

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6-docs#390]
https://github.com/grafana/xk6-output-kafka/pull/7 adds SASL authentication which required quite a bit of configuration options that will need documentation. 

This might also be a good time to discuss whether moving this documentation to the repo is a better idea :thinking:

**Comment by ppcano** [comment]
I am closing this issue as is a duplication of https://github.com/grafana/xk6-output-kafka/issues/12

> This might also be a good time to discuss whether moving this documentation to the repo is a better idea 🤔

This already happened. The Kafka documentation was removed because they were outdated. 

The kafka output does not seem to have a strong adoption. Should we document it again? If yes, I suggest opening a new issue.
