### ISSUE TITLE
Update built-in metrics 

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-docs#471]
There are up to 25 built-in metrics in k6.  The [current list](https://k6.io/docs/using-k6/metrics/#built-in-metrics) is missing a few such as WS, GRPC, and group duration.

WS and GRPC metrics are not common ones. Let's update the content to include all of them in a subtle way.

**Comment by yorugac** [comment]
The names of all builtins for reference: https://github.com/grafana/k6/blob/dae70006ca77767e456acafbdda284d064dbd882/lib/metrics/metrics.go#L27-L58

**Comment by na--** [comment]
FWIW, built-in metrics from websockets are specified here: https://k6.io/docs/javascript-api/k6-ws/socket/#websocket-built-in-metrics

Maybe that's better, we can document the metrics in their respective JS APIs instead of globally? And we can just link to these pages from the main metrics page?

**Comment by MattDodsonEnglish** [comment]
Builtin metrics, we're missing GRPC and Websockets.

https://github.com/grafana/k6/blob/master/metrics/builtin.go#L23-L30

**Comment by MattDodsonEnglish** [comment]
This should be fixed with and #1173 and #1174 .

I decided to move all the metrics to one single reference page, then link bidirectional (to reference from API doc, and vice versa). I thought this would be slightly better, guessing that most readers will look in the toplevel metrics doc before they look deep in the API reference docs (this is especially true from HTTP metrics, which most users encounter on their first test). But it's 6 on one side, half a dozen on the other :shrug: . 

Related issue: #1160
