### ISSUE TITLE
Do we really need to document setting options through a config file?

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-docs#688]
Currently, the options docs discuss using the `--config` flag to set options according to a JSON config file. I argue that this behavior should not be documented, at least not in the options section.

It creates a cluttered document, and the feature itself is more or less redundant---except to login or authenticate with the `k6 cloud` command. In all other cases, the `--config` flag just adds another thing to remember in the order of precedence.

If a user wants to set options in a separate file, they could either define their options in another `js` file. Or, if they wanted to use a JSON file, they could use `JSON.parse()` to parse out the JSON into a script option. This is what @na-- suggested in [a community thread](https://community.k6.io/t/scenario-config-file/1282). It's worth mentioning that that thread is about a very understandable confusion with the `--config` flag, and the very valid solution is to just...not use it.

Switching between API keys is _definitely_ a valid use of the `--config` flag though. So, why not mention it in the cloud docs, and not worry using the flag to set options?

## Proposed changes

- [ ] Remove mentions of setting options in the config file. 
- [ ] Keep the `--config` option in the "Options" reference but only to describe logging into cloud 
- [x] Add something about changing API keys and logging into multiple cloud accounts in the cloud docs
- [ ] Move the current example of how to set options with a config to a "hidden file" (not shown in the sidebar). That way, we have something to link to for any users who do use this niche way to set options.

This wouldn't break the feature of course, but it would leave it intentionally undocumented and make it unlikely that new users would stumble on it.

**Comment by ppcano** [comment]
> Counterpoint: using the --config flag lets the user separate configuration from logic. This adds modularization.

In 99%, we should recommend modularizing functionality/options using ES5 modules like the [k6-purina example](https://github.com/grafana/k6-purina/blob/main/main.js#L50). Not using  the `--config` option.

```javascript
// load test config, used to populate exported options object:
const testConfig = JSON.parse(open('./config/test.json'));

// combine the above with options set directly:
export const options = testConfig;
```

So, I am in favor of skipping the config option when detailing [how to set options and order of preference](https://k6.io/docs/using-k6/options/#where-to-set-options) to simplify k6 learning.

> Move the current example of how to set options with a config to a "hidden file" (not shown in the sidebar). That way, we have something to link to for any users who do use this niche way to set options

Agree. We can also reference this page from [here](https://k6.io/docs/using-k6/options/#config).

**Comment by na--** [comment]
Soft :-1: We probably won't ever deprecate support for config files, since it will be a super major breaking change - a lot of people use config files from my observations... :disappointed:  So I don't think we should hide this feature from the documentation, that seems like it will only add confusion, not reduce it :man_shrugging: Besides, the actual k6 option names are identical for the JSON config and for the exported JS `options`, so I am not sure I agree it adds a lot of clutter.

**Comment by MattDodsonEnglish** [comment]
But is there any reason to encourage using the `--config` flag? Since I wrote that, I realized that users can also change cloud API tokens through the environment variables.

>  a lot of people use config files from my observations..
Hey @na--  , just to confirm, do you mean that many users use config files in general, or that many users use the `--config` flag? That community thread that I linked was the only example I could find of use "in the wild," but of course you would know better.

And for people who already use it, nothing would break by undocumenting. If they needed the docs, we could have it in a separate "hidden" file https://github.com/grafana/k6-docs/commit/7f6275b22f3193374a43d4b3394ea8fad361da54 (or 
unhidden).

**Comment by na--** [comment]
> do they import in the script a file with the config options or do they use the [--config option](https://k6.io/docs/using-k6/options/#config)

Both, but if I have to bet, I'd bet that more users use `--config` compared to `JSON.parse(open('config.json'));`

@ppcano, my whole point was that _because_ we can't and won't deprecate `--config`, hiding mentions of it and explanation for it in the docs adds confusion, it doesn't remove it...

The new picture in https://github.com/grafana/k6-docs/pull/686 will just lead people to ask the question "ok, where in the priority list does --config fall?" in the forum, and other such questions that can currently answered in the docs.

**Comment by MattDodsonEnglish** [comment]
Hmm the scope of this is getting a bit more higher-level than the issue of `--config`, but I would say that we _do not_ need to document every possible functionality, especially if the functionality is redundant or sub-optimal.

I'm even wary of documenting discouraged uses, like RPS, too, but I understand that sometimes we need to maintain backwards compatibility. And, at least `--summary export` and `--RPS` have a certain brutal simplicity: it's not the best way, but it's the easiest. Is `--config` like that too?

Minimizing information overload is not only about docs, but about the overall UX of the system. k6 users are developers, and developers know that there are nearly infinite ways to potentially implement something. Keeping it to the best option removes unneeded analysis.

I guess this starts to open up a whole topic about the aesthetic goals of an application: what is more important, flexibility , simplicity, or performance?  It's like comparing the Python mantra "There should be one-- and preferably only one --obvious way to do it" against the Perl style of "there's more than one way to do it?. 

Does k6 have a stance here?

**Comment by na--** [comment]
I am very much a fan of the approach to have one way to do something, it's also what Go tries to do.

However, in the case of k6, when it comes to functionality, these old and obsolete options and functions still remain because removing them will be a somewhat major breaking change. And, given the fact that k6 is a tool you use to ensure the reliability of other systems, having your reliability tool break without any changes in your test code is quite the frustrating experience... :sweat_smile: So, in general, we've tried to make as few breaking changes as possible. We try to do that only when there is really no other way to implement or fix something and/or when when the upside is much, much better than the downsides.

So, the `--summary export` and `rps` options remain, even if there are better ways to do the same thing in recent k6 versions, we just document that fact. If we ever decide to completely deprecate them (e.g. remove the `rps` option because the new HTTP API will be much harder to write if we have to support it, or something like that), we'll start emitting a warning if they are used and still leave them enabled for a few k6 versions until we deprecate them completely.

However, when it comes to `--config`, I don't think it's either deprecated or even discouraged... :confused: What exactly are your arguments against it? That it adds another way to do the same thing you can already do from JS options? If so, then the same can sort of be said for environment options and CLI flags :sweat_smile: Extending the argument, we should just document the CLI flags or the JS options, not both :sweat_smile: 

In contrast to specific k6 options or features, the different ways of configuring k6 are meant to make usage of k6 easy in all sorts of contexts and use cases, for example:
- CLI flags allow for very easy iterative development and script debugging
- environment variables make running k6 in containers and CI systems super easy
- JS options and JSON config files allow users to check their test config along with their tests in source control
- JSON config files are a quick and easy way to support multiple test profiles

Mixing and matching all of these adds complexity, but is somewhat unavoidable (if you have multiple config sources, you need to merge them _somehow_) and allows for unparalleled flexibility. And while `--env config=config.json` and `JSON.parse(open(__ENV.config'));` is more powerful than just `--config config.json`, since you are able to modify and merge the resulting JS object, most users probably don't need it, so I don't see the problem of having both.

And yes, if I was writing k6 from scratch today, I would have probably started with only 1 or 2 config layers... :sweat_smile: But that doesn't necessarily mean we want to remove (or even discourage) then now that we already have and support them... :man_shrugging:

**Comment by MattDodsonEnglish** [comment]
I really appreciate the time you took type this all up @na-- !

For what it's worth, I've brought the --config flag back, and I'm not too sad about. I'm happy about the restructure is overall.
However, for the sake of argument...

I definitely agree that makers of reliability tools should be very careful about breaking things. But is undocumenting something a form of breakage? Serious question... I never thought about it before. 

> That it adds another way to do the same thing you can already do from JS options? If so, then the same can sort of be said for environment options and CLI flags 😅 Extending the argument, we should just document the CLI flags or the JS options, not both 😅

Well it's not exactly true, since there are some options which work in only CLI/ENV
(e.g. [compatibility mode](https://k6.io/docs/using-k6/options/#compatibility-mode)), and others that can only work in script/config (e.g. [hosts](https://k6.io/docs/using-k6/options/#hosts)).

Anyway, I think we can all agree that CLI flags are better for quick changes, one-timer, overrides, etc.
But even if the application/documentation goal was only to provide a single way to do something, we'd still need to document at least CLI/Env and Script/Config. So why not one of each?

Environment variables work better in with a whole devops buildchain. True, teams could also use flags in some way, but it'd be inconvenient.

On the other hand, I don't see a clear advantage of the config option. 

> JSON config files are a quick and easy way to support multiple test profiles

But is it much easier to use `--config ./config/test.json` over this?

```
const testConfig = JSON.parse(open('./config/test.json'));
```

Definitely there a few less characters. But, as you say:

> And while --env config=config.json and JSON.parse(open(__ENV.config)); is more powerful than just --config config.json, since you are able to modify and merge the resulting JS object, most users probably don't need it, so I don't see the problem of having both.

I think this is my main point. Whether to document it is not really a question of bad or good design, but of whether to trade off flexibility for simplicity. I don't think it's too bad to keep it in this case. But also I don't think feature maximalism is a good goal of the docs either.

**Comment by na--** [comment]
> But is undocumenting something a form of breakage? Serious question... I never thought about it before.

Hmm :thinking: In most cases, I'd say yeah, kind of...

In the past, we've used the fact that some already existing sub-optimal behavior of k6 was undocumented to mean that it was undefined behavior. So we could fix/improve it without considering that a real breaking change. We still usually mentioned it in the release notes under "breaking changes", to make it obvious we made the change, but we didn't consider that it fell under the same backwards compatibility guarantees we usually try to provide for everything else...

In general, when it comes to user-facing APIs and behaviors, the docs are the de-facto source of truth. Unless there has been an obvious mistake in the docs, if some k6 behavior doesn't match what we say in the docs, we usually will consider that a bug and fix the k6 behavior. That is one of the reasons I am very much against un-documenting existing things and making them essentially undefined behavior. The other major reason is that it will just lead to more questions on the forum if people can't find the info in the docs.

> On the other hand, I don't see a clear advantage of the config option.

It's mostly just a more convenient and less error-prone way of configuring k6 when you don't require very complicated or dynamic configuration :man_shrugging: Though you also currently can't configure some things (like outputs, including the cloud output) from the JS exported `options`, while you can configure them from the JSON configs.
