### ISSUE TITLE
Create a WIP icon to help highlight features which are still being worked on

### ISSUE THREAD

**Issue by ankur22** [grafana/k6-docs#729]
We're building a new extension called `xk6-browser` and along with it with are documenting the features that work and are currently in progress. We'd like to document the work in progress features too so that our end-users know what's coming and can easily keep track of them. We're currently using the construction emoji 🚧 like so:

<img width="866" alt="Screenshot 2022-07-11 at 17 00 02" src="https://user-images.githubusercontent.com/1112428/178450714-ee47041f-d01e-4fc7-a0bd-57c9267a4978.png">

The issue with using emojis is that we can't guarantee that the correct fonts/character sets will be installed on the end-users system, so we need an icon to replace this emoji (SVG?) -- more context here: https://github.com/grafana/k6-docs/pull/722#discussion_r916571824.

**Comment by MattDodsonEnglish** [comment]
@ankur22 I think we can close this, right? As far as I can tell, the pages now have nice WIP icons: https://k6.io/docs/javascript-api/xk6-browser/#browser-level-apis

Or is there more work to do here?

**Comment by imiric** [comment]
@MattDodsonEnglish Maybe this issue should be more generic, as it's not about just the WIP icon, but icons on the site in general.

We use Unicode font glyphs ("emojis") for all icons, whose rendering is system/browser-dependent. For example, they don't show up for me on Chromium/Linux:

![2022-08-29-154233_889x365_scrot](https://user-images.githubusercontent.com/1009277/187216340-71486fc9-d0e6-4d03-b592-e1c79d441c84.png)

But do work fine on Firefox/Linux. :shrug:

So instead of relying on system fonts, all icons should be converted to SVGs. Or, at the very least, we should load an icon font that is known to contain the glyphs, but going with SVGs would be more reliable.

**Comment by MattDodsonEnglish** [comment]
@imiric How about we close this issue and make a new issue about glyphs/SVG icon support specifically? I prefer having issues more atomic to make it easier to link specific problems to commits. (This is mainly a comment to me; I've made some issues of sprawling scope).

But, this is definitely something to fix. I just realized even the top-level docs page has missing icons in Chrome.

How it looks on my Linux machine today.
- ![image](https://user-images.githubusercontent.com/47385188/187239870-7eafd259-12f8-4c13-a9a7-86fa1729fb5e.png)

**Comment by imiric** [comment]
If you follow the [discussion that spawned this issue](https://github.com/grafana/k6-docs/pull/722#discussion_r916571824), I think that was @ankur22's original intention, and he only mentioned the WIP icon as an example.

So I'd prefer updating the title/description of this issue, but if you want to create a new one, go ahead.

And yeah, it's also an issue in the "Running k6" section.

**Comment by MattDodsonEnglish** [comment]
I get you.

Ankur explained the issue very well, but it was grounded in a specific need. So I made a new issue, just to keep the top-level comment of the issue focused on the central problem. I'm also not a big fan of changing issue titles, because it can make the initial discussion seem somewhat off-topic or incoherent.

New issue:
https://github.com/grafana/k6-docs/issues/781
