### ISSUE TITLE
Be consistent with "exported/global" function/callbacks

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-docs#845]
We should be consistent in the way to describe the `setup`, `teardown`, and `handleSummary` functions.

The discussion started at https://github.com/grafana/k6-docs/pull/842#discussion_r1002789959

Proposals: 
- callback
- exported functions
- global functions
- hooks
- ....

**Comment by pablochacin** [comment]
I think hooks reflect better the intended use of these functions as a way to "[change or augment the behavior](https://en.wikipedia.org/wiki/Hooking)" of k6. 

Callback is not accurate in the sense that generally a callback function is passed when calling another function call as way to process events or the result of that function call. 

Global and exported are too generic to express their purpose.

**Comment by MattDodsonEnglish** [comment]
I'm going to represent the ignorant.

Why do we need to call them anything but functions? What extra behavior do the suggested terms imply that's necessary for the reader to know?

> Callback is not accurate in the sense that generally a callback function is passed when calling another function call as way to process events or the result of that function call.

Is there no other function call?
It seems like all these functions exist in the context of some other function that's _outside_ the k6 script, is that correct? (If not, what do they export _to_?). Is the behavior typical in the JavaScript world? Can someone provide an example?

As an outsider, I can say that the following questions always confused me:
- To what is `default` exported?
- From where did the `data` argument passed to handleSummary come from?

Beyond terminology, it might be useful to add some section that explains this run time behavior. Even the behavior is common to the JS world, given the unique use of k6, we can't expect writers of k6 scripts to be experienced JS programmers.

I like both "hook" and "callback". I'd use whichever is most common in the and accurate. For now, I choose `callback` because it has an [MDN page](https://developer.mozilla.org/en-US/docs/Glossary/Callback_function), while `hooks` appear in MDN only in the context of React. I'd change my mind in a heartbeat if "hook" is definitely more accurate (sorry @pablochacin , I trust your statement, but I just don't understand the behavior very well).

 But whether we choose "hook", "callback", or "something else," the questions for me remain:
- If it's a callback, what is calling back?
- If it's a hook, what call is being interrupted?
- Will it help users to know the answers to these questions? If it won't, why can't we just call them "functions?"

**Comment by ppcano** [comment]
@MattDodsonEnglish 

The feedback was that callback is not accurate. @mstoykov pointed from the [MDN article](https://developer.mozilla.org/en-US/docs/Glossary/Callback_function):

> callback is a function passed into another function as an argument


Agree here. NodeJS APIs were callback-oriented before Promises. See [NodeJS FS API](https://nodejs.org/api/fs.html).


<img width="306" alt="Screenshot 2022-10-25 at 09 29 26" src="https://user-images.githubusercontent.com/825430/197716506-ba4979e0-8ff7-47f2-9981-1f8c41c82176.png">

------------------



More examples:

1.  [React hooks](https://retool.com/blog/the-react-lifecycle-methods-and-hooks-explained/):
- react hooks are different - they are imported functions.
- But `componentDidMount `, `componentWillMount` are similar and called lifecycle methods


2. [VueJS](https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html) names it Lifecycle hooks.

> There are also other hooks which will be called at different stages of the instance's lifecycle, with the most commonly used being [mounted](https://vuejs.org/api/options-lifecycle.html#mounted), [updated](https://vuejs.org/api/options-lifecycle.html#updated), and [unmounted](https://vuejs.org/api/options-lifecycle.html#unmounted).


3. [Kubernetes Container Lifecycle hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/)
> use the Container lifecycle hook framework to run code triggered by events during their management lifecycle.



------------------

Currently, I am between `lifecycle functions` and `lifecycle hooks` - leaning towards `lifecycle functions` for simplicity.

Thinking about other potential future cases,  k6 could run multiple times a lifecycle "XYZ" for other types of events. But I don't think this new capability would change the way we name it now.

**Comment by MattDodsonEnglish** [comment]
I've updated my questions above since @mstoykov pretty much answered all of them. (read the collapsible).

Now that I understand that there isn't really a meta-JS environment, I really like "lifecycle function". We already use lifecycle, and "function" doesn't carry much extra meaning.

Hook seems pretty good to, since it does intercept. [Mocha's hook doc](https://mochajs.org/#hooks) is very clear.

I vote function because it's more generic. Hook seems good to. We can still say callback, but only when describing a callback in a function in the k6 script. (That is, a typical JS callback :wink: ).

**Comment by MattDodsonEnglish** [comment]
After we come to a consensus:

- [ ] Update Lifecycle doc
- [ ] Update glossary
