### ISSUE TITLE
How to handle not up-to-date extensions

### ISSUE THREAD

**Issue by renehernandez** [grafana/k6-docs#931]
When trying to use the [xk6-faker](https://github.com/szkiba/xk6-faker) extension, I realized that it doesn't work with the latest k6 release due to the breaking API changes for extensions. So, I ended up upgrading the code in my own fork, to make it work.

When I went to open a PR to upstream the changes in the extension, I found out there are already 2 PR (one of them from April) that are attempting to address the same issue, so there are no signs of traction on the repo at this point.

Any workarounds for this? Is there any options to add an alternative xk6-faker repo as an extension (can we have it with a somewhat different name?).

Looking through the k6/docs issues, this relates https://github.com/grafana/k6-docs/issues/852. We need better documentation discovery about how well maintained are extensions

**Comment by imiric** [comment]
Hi Rene, thanks for opening this issue.

Unfortunately, this is a general problem with extensions supported by users from the community. Sometimes they move on and don't want to keep maintaining their extensions when new versions of k6 are released with possibly breaking changes.

I think there are few ways to work around this:

1. If you don't need the latest version of k6, try building the extension with an older version. E.g. `xk6 build v0.37.0 --with github.com/szkiba/xk6-faker@latest`.

2. If there's already a PR fixing the issue, try building against the repo that has the fix. E.g. `xk6 build latest --with github.com/rammstein4o/xk6-faker@latest`.

   Though you might run into import issues in some cases, because of the change of URL.

3. If the above is not sufficient, you can always fork your own version of the extension, do the relevant fixes, and continue to use that instead.

   If the original extension author is unresponsive, then you might want to propose your change to k6-docs so that we can update our recommended extension list to link to your fork instead.

   The name of the extension can probably stay the same, since the distinction will be in the maintainer name.


But you're right that we need better discoverability into the state of each extension. We'll hopefully work on that change soon.

**Comment by renehernandez** [comment]
@imiric Thanks for the reply.

I went ahead already and created a fork at [renehernandez/xk6-faker](https://github.com/renehernandez/xk6-faker) that works with up-to-date k6 binaries (v0.41.0) and we are using that internally at work

If it makes sense, I can open an MR to add my fork as an up-to-date extension. I am going to be working with k6 with the foreesable future on a regular cadence so I should have the bandwidth to keep the extension up-to-date

**Comment by imiric** [comment]
It's great that you found an approach that works for you @renehernandez.

We've started the process internally to define some guidelines about this, but don't have a clear answer yet, so please hold off on creating that PR. We'll let you know here as soon as we have an update.
